name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  schedule:
    # run every Tuesday at 3 AM UTC to catch breakage caused by changes to external dependencies (libraries, platforms)
    - cron: "0 3 * * 2"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - arduino:samd:arduino_zero_edbg
          - arduino:samd:mkr1000
          - arduino:samd:mkrzero
          - arduino:samd:mkrwifi1010
          - arduino:samd:nano_33_iot
          - arduino:samd:mkrfox1200
          - arduino:samd:mkrwan1300
          - arduino:samd:mkrwan1310
          - arduino:samd:mkrgsm1400
          - arduino:samd:mkrnb1500
          - arduino:samd:mkrvidor4000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            # Install the AudioZero library from the local path
            - source-path: ./
            - name: SD
          sketch-paths: |
            - examples
